/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#6063ee",
        "inverse-primary": "#c0c1ff",
        "surface-container-low": "#f3f4f5",
        "tertiary-fixed": "#ffdcc5",
        "outline-variant": "#c7c4d7",
        "secondary-fixed-dim": "#c0c1ff",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#bdbefe",
        "on-tertiary-container": "#fffbff",
        "surface-bright": "#f8f9fa",
        "on-background": "#191c1d",
        "primary-fixed-dim": "#c0c1ff",
        "tertiary-container": "#b55d00",
        "secondary-fixed": "#e1e0ff",
        "surface-container-highest": "#e1e3e4",
        "secondary": "#575992",
        "surface-dim": "#d9dadb",
        "on-secondary-fixed-variant": "#404178",
        "primary-fixed": "#e1e0ff",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#301400",
        "on-error-container": "#93000a",
        "tertiary": "#904900",
        "inverse-surface": "#2e3132",
        "surface-tint": "#494bd6",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-secondary-fixed": "#13144a",
        "on-secondary-container": "#494b83",
        "surface-container-high": "#e7e8e9",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#07006c",
        "on-secondary": "#ffffff",
        "on-primary-container": "#fffbff",
        "surface": "#f8f9fa",
        "surface-container": "#edeeef",
        "on-surface": "#191c1d",
        "on-primary": "#ffffff",
        "on-surface-variant": "#464554",
        "outline": "#767586",
        "tertiary-fixed-dim": "#ffb783",
        "background": "#f8f9fa",
        "inverse-on-surface": "#f0f1f2",
        "surface-variant": "#e1e3e4",
        "primary": "#4648d4",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#703700"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
